name: Snap CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # Allow manual trigger
  workflow_dispatch:

env:
  SNAP_NAME: stack-utils

jobs:
  test:
    runs-on: [ self-hosted, linux, amd64, medium, noble ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.x'
      - name: Hardware info tests
        run: |
          go test -v -count 1 ./pkg/hardware_info/...
      - name: Selector tests
        run: |
          go test -v -count 1 ./pkg/selector/...
      - name: Type tests
        run: |
          go test -v -count 1 ./pkg/types/...
      - name: Util tests
        run: |
          go test -v -count 1 ./pkg/utils/...
      - name: Stack validation tests
        run: |
          go test -v -count 1 ./pkg/validate/...

  build:
    name: Build
    needs: [ test ]
    strategy:
      matrix:
        runs:
          - architecture: amd64
            runner: [ self-hosted, linux, amd64, medium, noble ]
          - architecture: arm64
            runner: [ self-hosted, linux, arm64, medium, noble ]
    runs-on: ${{ matrix.runs.runner }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build snap
        uses: snapcore/action-build@v1
        id: snapcraft

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{env.SNAP_NAME}}_${{github.run_number}}_${{matrix.runs.architecture}}
          path: ${{ steps.snapcraft.outputs.snap }}
          if-no-files-found: error

      - name: Publish snap
        uses: snapcore/action-publish@v1
        if: github.ref == 'refs/heads/main'
        env:
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.STORE_LOGIN }}
        with:
          snap: ${{ steps.snapcraft.outputs.snap }}
          release: latest/edge/ci
